name: AutoCorrect

on:
  pull_request:
    branches: [main]

jobs:
  autocorrect:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Nix
        uses: https://github.com/cachix/install-nix-action@v30
      - name: AutoCorrect check
        run: |
          files=$(git diff --diff-filter=AM --name-only ${{ forgejo.event.pull_request.base.sha }})
          if [ -z "$files" ]; then
            echo "No files to check."
            exit 0
          fi
          nix run nixpkgs#autocorrect -- \
          --lint \
          --no-diff-bg-color \
          $files
